components:
  ironedge/kernel:
    config:
      processor:
        class:                \IronEdge\Component\Kernel\Config\Processor
        priority:             99
    logger:
      instances:
        default:
          handlers:
            - default
      handlers:
        default:
          type:                 stream
          level:                DEBUG
          stream:               %kernel.logs_path%/default.log
      formatters:
        line:
          serviceId:            logger.formatter.custom_line_formatter
  ironedge/cli:
    commands:
      cache_clear:
        class: \IronEdge\Component\Kernel\Console\Command\CacheClear