components:
  ironedge/kernel:
    config:
      processor:
        class:                \IronEdge\Component\Kernel\Config\Processor
        priority:             -10
    loggers:
      kernel:
        level:                DEBUG
        handlers:
          type:                 stream
          path:                 %kernel.logs_path%/kernel.log